# 파일 위치: orbiton.ai/docker-compose.yml
# GPU + GeoIP + 경로 통일 + 실행 순서 + 컨테이너 명시 + 재시작 정책 포함

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: orbitonai-backend
    container_name: orbiton-backend
    ports:
      - "8000:8000"
    volumes:
      - ./GeoLite2-Country.mmdb:/backend/GeoLite2-Country.mmdb
    environment:
      - OLLAMA_USE_GPU=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
  build:
    context: .
    dockerfile: frontend/Dockerfile
  image: orbitonai-frontend
  container_name: orbiton-frontend
  ports:
    - "5173:5173"
  depends_on:
    - backend
  restart: unless-stopped

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: orbitonai-ollama
    container_name: orbiton-ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
