# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: orbitonai-backend
    container_name: orbiton-backend
    ports:
      - "8000:8000"
    volumes:
      - ./GeoLite2-Country.mmdb:/backend/GeoLite2-Country.mmdb
    environment:
      - OLLAMA_USE_GPU=1
      - PYTHONPATH=/ 
      - DATABASE_URL=${DATABASE_URL}
      - CLICKUP_API_KEY=${CLICKUP_API_KEY}
      - CLICKUP_LIST_ID=${CLICKUP_LIST_ID}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: orbitonai-frontend
    container_name: orbiton-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend

  ollama:
    build:
      context: .
      dockerfile: ollama/Dockerfile
    image: orbitonai-ollama
    container_name: orbiton-ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
